### ISSUE TITLE
Error: Failed to open file.

### ISSUE THREAD

**Issue by Jahshua1** [AltimorTASDK/ClientSettingsEditor#10]
Whenever I try to get my Fortnite sensitivity on any platform this error appears.

**Comment by Cosmex** [comment]
Yes I'm having the same problem i tried uninstalling the game so it would rewrite the files, but it didn't work hopefully there's a solution to this.

**Comment by ThFate** [comment]
Same issue

**Comment by AltimorTASDK** [comment]
Fixed
