### ISSUE TITLE
Fucking Help us, Make a ClientSettingsEditor 1.5

### ISSUE THREAD

**Issue by JubayerA07** [AltimorTASDK/ClientSettingsEditor#11]
Im also having Problems when opening The editor:Failed to open file, lol i just made the title rude so u can look at it

**Comment by LLNPR1D3** [comment]
listen kid ... like... u are not paying him a single dollar , what makes you think you can demand that.. , get good man a single number is not messing all your aim and it is not your solution to became goated , be respectful.

**Comment by AltimorTASDK** [comment]
ClientSettings.sav is now encrypted, so this isn't as simple of a fix as before.

**Comment by 00AhmedAshraf** [comment]
AltimorTASDK there is a solution or not please

**Comment by bostinha222** [comment]
i think he is working on it guys, he never let us down before, please just be patient

**Comment by oluittv** [comment]
AltimorTASDK I feel like you don't get this enough, so thank you for your work man, a lot of people appreciate you for making this app 👏

**Comment by AltimorTASDK** [comment]
Fixed
