### ISSUE TITLE
Client settings 1.4 fails to desterilize file on cloud import 

### ISSUE THREAD

**Issue by Intention1x** [AltimorTASDK/ClientSettingsEditor#12]
When me and everyone else who owns the app, try to use cloud import and then client settings.sav it fails to desterilize the file. I personally swapped my sensitivity and I’m trying to become the best player possible. It would be great if you could please create a client settings 1.5 quickly. Everyone and me would appreciate it.

**Comment by bostinha222** [comment]
agreed

**Comment by Artem1539** [comment]
help me please, I cannot find its sensu

**Comment by AltimorTASDK** [comment]
Fixed
