### ISSUE TITLE
ClientSettingsEditor error

### ISSUE THREAD

**Issue by ricardovezzani** [AltimorTASDK/ClientSettingsEditor#13]
When I open my ClientSettings an error happens, follow the image
![Screenshot_28](https://user-images.githubusercontent.com/55511550/65181097-ae5d1080-da34-11e9-9341-a895574d856f.png)

**Comment by codigokizero** [comment]
a mi me ocurre lo mismo, pudo solucionar?

**Comment by AltimorTASDK** [comment]
Fixed
