### ISSUE TITLE
DON'T OPEN THE FILE

### ISSUE THREAD

**Issue by MKOGAMES** [AltimorTASDK/ClientSettingsEditor#16]
well I want to report a serious error in the program "client settings editor", because it turns out that today (09/20/19) I saw that the program no longer opened the client settings file of fortnite, it seemed weird because it always I made it easy and never had mistakes, so I want you to see where the problem may be
![Captura de pantalla (100)](https://user-images.githubusercontent.com/55601660/65355250-218e9000-dbb7-11e9-8bc8-fd45425b091e.png)
  I also even tried to access my settings through the "cloud import" option but when I access some method to do it, for example google, I get a screen from the epic games page telling me what it says in this image.
![Captura de pantalla (101)](https://user-images.githubusercontent.com/55601660/65355774-57804400-dbb8-11e9-8243-879ce21a4d23.png)
and one more thing, when I try to enter through my account and not through google or facebook, etc., I got this sale, but when I clicked on this file, nothing just comes out and it just goes blank
![Captura de pantalla (102)](https://user-images.githubusercontent.com/55601660/65355783-5d762500-dbb8-11e9-904c-03dbc93196ce.png)
well I wait for an answer, because they had made some changes in my sensibility and wanted to pass them to the sensibility of koovaks fps aim trainer and well as I get angry that, I hope they find a solution.

**Comment by AltimorTASDK** [comment]
Fixed
