### ISSUE TITLE
UPDATE IT

### ISSUE THREAD

**Issue by kehbadimek** [AltimorTASDK/ClientSettingsEditor#18]
Are you ever going to update this or what? It takes so long... Did I bought Kovaaks for nothing or what?

**Comment by r3ggie95** [comment]
Dude what is your issue ? He said that it is encrypted now and that it will be a while. You can still do kovaak just put it on slider. Itsjerian did a video on. Let him do his thing without get spammed with rude comments

**Comment by TheRelow** [comment]
> Dude what is your issue ? He said that it is encrypted now and that it will be a while. You can still do kovaak just put it on slider. Itsjerian did a video on. Let him do his thing without get spammed with rude comments

He takes money for it. He should fix the problem, but it's been a really long time, and the problem has not been fixed

**Comment by r3ggie95** [comment]
If it was a simple fix I’m sure he would have fixed it by now. Epic purposely encrypted the files. It was some random accident that mess up everything. They don’t want us in the files.

**Comment by AltimorTASDK** [comment]
> > Dude what is your issue ? He said that it is encrypted now and that it will be a while. You can still do kovaak just put it on slider. Itsjerian did a video on. Let him do his thing without get spammed with rude comments
> 
> He takes money for it. He should fix the problem, but it's been a really long time, and the problem has not been fixed

I don't take money for it.

**Comment by AltimorTASDK** [comment]
Fixed. Calm your entitlement lul
