### ISSUE TITLE
Workaround while the ClientSettingsEditor is unavailable

### ISSUE THREAD

**Issue by KovaaK** [AltimorTASDK/ClientSettingsEditor#19]
Heya,

I see a lot of people have been having trouble since Epic changed the format of (or encrypted) the ClientSettings.sav file.  Since most people are trying to use this tool to get their precise mouse sensitivity instead of the value that is rounded in the options menus, I want to let people know that there is an alternative in using the Sensitivity Matcher script that I released a while back.  I had a friend make a quick video showing how to use it in Fortnite - https://www.youtube.com/watch?v=GbIn7FKfphQ.

Hope this helps!
-Garrett "KovaaK" Krutilla

**Comment by AltimorTASDK** [comment]
Fixed. Thanks for your work KovaaK.
