### ISSUE TITLE
[REQUEST] Session/Cookie Saving

### ISSUE THREAD

**Issue by rierei** [AltimorTASDK/ClientSettingsEditor#2]
Every time the program is opened it requests to login with epic games account. If the account have two factor authentication, every time will be requested the security code.

When acessing the link https://launcher-website-prod07.ol.epicgames.com/epic-login there is a checkbox "Remember" which dont apper on this client.

Can be Session/Cookie saving possible?

**Comment by AltimorTASDK** [comment]
This is possible, I'm just cautious about it because I don't want to store credentials or auth tokens in a way that could be a target for malware. Right now you can use any of the single sign on options through your browser and your browser will remember everything.

**Comment by rierei** [comment]
Sorry, i dont understand what you have said, what is the relation from logging in the browser and this program? Cause logging on the browser wont allow me using this client, cause it have his own browser.

I know that storing the credentials could be dangerous. Maybe letting something like Chromium handle that should be more secure?

This CSS code, if i remove it the session can be remembered?
```
.resetPass, .switchMode, #rememberMeCheckContainer
{
    display: none;

}
```

Thanks for the quickly reponse!

**Comment by AltimorTASDK** [comment]
If you use google/facebook/whatever single sign-on it opens in your browser.

**Comment by rierei** [comment]
I linked my Epic account with Google and now i just need to login with sign-on, no Two Factor needed. Thank you!
