### ISSUE TITLE
cloud download failure 

### ISSUE THREAD

**Issue by f4nch** [AltimorTASDK/ClientSettingsEditor#22]
after entering clientsettings such a thing began to happen
https://ibb.co/2P83T9j

**Comment by lucaspfl** [comment]
You will need to delete everything on client settings, you can keep the Sensitivity X Y, TargetingSlow and ScopedSlow, the file generated by client settings is too big and do bugs with cloud, when you deleted all columns  and keeped the sensitivy the file will be light export to cloud

**Comment by f4nch** [comment]
thank you very much it helped

**Comment by lucaspfl** [comment]
You're welcome
