### ISSUE TITLE
There is another issue and i recently swapped   my sensitivity and now i cant practice my aim. Please fix your software immediately

### ISSUE THREAD

**Issue by Intention1x** [AltimorTASDK/ClientSettingsEditor#26]
It says failed to deserialize file.exeption: Unable to red beyond the end of the stream.   
Everyone has this issue, nobody can use to software, Please create clientsettings 1.6 immediately

**Comment by AltimorTASDK** [comment]
being a demanding ass and spamming 6 issues isn't going to get it fixed any faster
