### ISSUE TITLE
Some things are not appearing

### ISSUE THREAD

**Issue by HughSparks** [AltimorTASDK/ClientSettingsEditor#3]
When I try to load my config It does not let me see stuff like mouse sens. By does not let me i mean it doesn't show up. When I load it through the saved files i can see my sens but not my ads. Any tips or tricks.

Cloud import
![image](https://user-images.githubusercontent.com/28938999/59558534-6946bf80-8fa9-11e9-8c7a-70837ae2d8a6.png)

File Open
![image](https://user-images.githubusercontent.com/28938999/59558567-06a1f380-8faa-11e9-8d64-dc1a6b82e9dd.png)

**Comment by AltimorTASDK** [comment]
Options are only written to the file once you've changed them in-game. You can also duplicate a setting of the same data type and change the name of the duplicate.
