### ISSUE TITLE
Error message: failed to deserialize file

### ISSUE THREAD

**Issue by Intention1x** [AltimorTASDK/ClientSettingsEditor#34]
I get this error upon clicking cloud import. After asking around everyone I have contacted get the same error message on client settings 1.5. Please come out with client settings 1.6, the community is relying on you and it would be appreciated if you could get this fix/ new version out as soon as possible, much appreciated, intentionz

**Comment by AltimorTASDK** [comment]
what is wrong with you, why do you keep spamming issues

i'm going to fix it when i have time to, spamming me won't make that any sooner

**Comment by Intention1x** [comment]
Sorry, didn’t mean to annoy you. Just frustrating the software is no longer working, and I know it’s not your fault and I understand you have stuff to do but please try your best to get it fixed as soon as possible, thank you for letting me know you will get it fixed soon. Sorry once again
