### ISSUE TITLE
Do you have any idea when the software will be operating again?

### ISSUE THREAD

**Issue by Intention1x** [AltimorTASDK/ClientSettingsEditor#37]

**Comment by zw5** [comment]
Holy shit

**Comment by cupidmedusa** [comment]
Thanks AltimorTASDK for all you do. We appreciate this aim trainer!

**Comment by Intention1x** [comment]
This is not a aim trainer its a software for finding your exact sensitivity in fortnite. its been broken for roughly 3 weeks nown
