### ISSUE TITLE
Patch 9.40: 'Failed to deserialise file. Exception: Unable to read beyond the end of the stream.'

### ISSUE THREAD

**Issue by ghost** [AltimorTASDK/ClientSettingsEditor#4]

**Comment by iTzNuumite** [comment]
I am also experiencing the same issue as OP. I had to reset my PC and forgot to write down the config sensitivity.

**Comment by ghost** [comment]
@iTzNuumite In your case, shouldn't your sensitivity have been preserved since the config is downloaded upon first game launch? Have you reset your game settings?

I'm guessing the newly added options have some relation to this. As a workaround, it may work to upload an empty config using the Client Settings Editor, then see if you can open the config after launching and closing the game once. Keep in mind you'll lose all of your settings this way though.

**Comment by AltimorTASDK** [comment]
Could you upload a copy of your ClientSettings.sav? I don't currently have Fortnite installed.

**Comment by iTzNuumite** [comment]
> @iTzNuumite In your case, shouldn't your sensitivity have been preserved since the config is downloaded upon first game launch? Have you reset your game settings?
> 
> I'm guessing the newly added options have some relation to this. As a workaround, it may work to upload an empty config using the Client Settings Editor, then see if you can open the config after launching and closing the game once. Keep in mind you'll lose all of your settings this way though.

Honestly, I don't know what your actual problem is besides the error. all I'm saying is I'm experiencing the same error when trying to import from the cloud and from the file. I'm assuming its cause of the recent update. I cant see the .sav file due to the error and the other .sav file in another folder doesnt have my sens in it. the in game setting are fine my senses are preserved. the problem for me is i need the config sens so  i can enter them into kovaaks because kovaaks doesnt save them to my steam account or whatever. the attached file might be the right cloud im not sure yet i would know once ive seen the config sens... 


[ClientSettings (3).zip](https://github.com/AltimorTASDK/ClientSettingsEditor/files/3412663/ClientSettings.3.zip)

**Comment by iTzNuumite** [comment]
Fixed the issue by uninstalling fortnite and deleting the fortnite game folder from the appdata. also had to reset all my settings and re-enter all my settings.

**Comment by billabonGS4** [comment]
Same issue 
Can you fix it pls ?

**Comment by AltimorTASDK** [comment]
I updated the editor to support the latest version of Fortnite and added name previews for input binding and HUD visibility mappings so you can see what each entry is without having to expand it. I also made it display the terse C++ type names for map key/value types.

**Comment by bostinha222** [comment]
> I updated the editor to support the latest version of Fortnite and added name previews for input binding and HUD visibility mappings so you can see what each entry is without having to expand it. I also made it display the terse C++ type names for map key/value types.

not working anymore

**Comment by Einsten01** [comment]
I having the same issue now. 09/14/19

**Comment by oPORTLANDo** [comment]
I literally am having this issue as we speak too Einsten whats your discord maybe we can try and find a solution together add me if you have discord my name is oPORTLANDo #2512

**Comment by f4nch** [comment]
https://ibb.co/qJHqjJ5
https://ibb.co/b6vdJSG

all the same does not work

**Comment by ThFate** [comment]
Same issue

**Comment by FahadSaleem** [comment]
Same issue, not working

**Comment by ricardovezzani** [comment]
same issue

**Comment by HeatGG** [comment]
Failed to deserialize file. Exception : Unable to read beyond the end of stream 

This issue is annoying I want a  fix asap Do it as fast as u guys can pls
