### ISSUE TITLE
failed to deserialize file

### ISSUE THREAD

**Issue by Urento** [AltimorTASDK/ClientSettingsEditor#42]
please fix this I need this program to change my sens and every time I try to one the File or Cloud Import it this error is appearing (title). Please fix this

**Comment by 4g3v** [comment]
I might have fixed this issue. Use this version and tell me if there are still any problems.
https://github.com/4g3v/ClientSettingsEditor/releases/tag/1.6

**Comment by Urento** [comment]
Yes it works now thanks i love you
