### ISSUE TITLE
OK message error 

### ISSUE THREAD

**Issue by yugosmurff** [AltimorTASDK/ClientSettingsEditor#5]
Hello , so i downloaded the software and then what i do (i sent some screenshots ) 
1 - Extract it 
2 - Execute ClientSettings.exe as administrator 
3 - Click on Open 
4 - Click on Cloud Import 
5 - Loggin on my MAIN account ( the one i want the config from )
6 - Then select my config file ( ClientSave.Sav ) [ All my settings appears in the window and are all goods ] 
7 - Click on Cloud Export 
8 - Double click the config file ( ClientSave.Sav ) 
9 - A message appear ( Status : OK ) i can only press OK and nothing happend 
The loggin window to log on my secondary account which one i wanted to export the config on didnt appear.....

![Image1](https://user-images.githubusercontent.com/53280937/61836321-22899680-ae80-11e9-9612-5f12b273541c.png)
![image2](https://user-images.githubusercontent.com/53280937/61836322-22899680-ae80-11e9-8563-163df4dce1cc.png)
![Image3](https://user-images.githubusercontent.com/53280937/61836323-23222d00-ae80-11e9-9d36-b81f88ddd663.jpg)
![image4](https://user-images.githubusercontent.com/53280937/61836324-23222d00-ae80-11e9-9b73-169fe182ca63.png)
![image5](https://user-images.githubusercontent.com/53280937/61836325-23222d00-ae80-11e9-9385-75ff5714ad8c.png)
![image7](https://user-images.githubusercontent.com/53280937/61836327-23222d00-ae80-11e9-96ce-db855f02e5de.png)
![image8](https://user-images.githubusercontent.com/53280937/61836328-23bac380-ae80-11e9-9605-a3cd0d9b67d1.png)

**Comment by AltimorTASDK** [comment]
Once you're logged in, you stay logged in until you close the editor. The "OK" message is informing you that you've successfully exported to the cloud. For now, you can work around this by saving your config to disk, restarting the editor, opening the config, and exporting it to your other account.
