### ISSUE TITLE
When are you fixing your software that everyone has been waiting on for multiple weeks

### ISSUE THREAD

**Issue by Intention1x** [AltimorTASDK/ClientSettingsEditor#53]
@AltimorTASDK

**Comment by clearbucketLabs** [comment]
The config file is encoded now.  it was not any time before...  this won't work unless it's decoded first, if it's possible.  i wouldn't waste my time figuring it out based on the issues posted here.  you all are ungrateful children.   it's open source, go ahead and figure it out yourself.

**Comment by Intention1x** [comment]
What the fuck does that even mean, I’m not a coder
