### ISSUE TITLE
Failed to deserialize file error

### ISSUE THREAD

**Issue by geedaniel** [AltimorTASDK/ClientSettingsEditor#6]
I tried both ways to upload file but I get an erro saying "Failed to deserialize file. Exception unable to read beyond the end of the stream.

**Comment by AltimorTASDK** [comment]
Did you download the latest release?

**Comment by sriram407** [comment]
Same issue here

**Comment by P0STA** [comment]
I am having the same issue as well, very frustrating. Has anyone came up with an answer?

**Comment by P0STA** [comment]
Could this be an issue regarding a virus protection?

**Comment by AltimorTASDK** [comment]
Are you all using the latest version (v1.4)?

**Comment by P0STA** [comment]
no say version 1.3

**Comment by P0STA** [comment]
That is the only version I see available.

**Comment by P0STA** [comment]
ok this version 1.4 has fixed issues. Thanks!

**Comment by Jocky23** [comment]
I have this issue too even on the latest version 1.5, anyone have answers to the problem
