### ISSUE TITLE
 ClientSettingsEditor version 1.5 with problem

### ISSUE THREAD

**Issue by reiart** [AltimorTASDK/ClientSettingsEditor#69]
RULE THIS BROTHER CUSTOMERTTINGS EVERY TIME COMES WITH THE SAME PROBLEM AFTER A TIME IN THE VERSION IT COMES WITH THE ERROR THAT CAN'T READ THE FILE AFTER THE FLOW !!! RELEASES VERSION 1.6 !!!!
![image](https://user-images.githubusercontent.com/55648268/71526512-103fd880-28b6-11ea-929b-8a8e616454bb.png)

**Comment by 4g3v** [comment]
I might have fixed this issue. Use this version and tell me if there are still any problems.
https://github.com/4g3v/ClientSettingsEditor/releases/tag/1.6

**Comment by reiart** [comment]
> Eu posso ter corrigido esse problema. Use esta versão e me diga se ainda há problemas.
> https://github.com/4g3v/ClientSettingsEditor/releases/tag/1.6


I click to open and it won't, it just doesn't open anything. thanks for the help, if you can fix this mistake I appreciate 
![image](https://user-images.githubusercontent.com/55648268/71792149-56afd880-3016-11ea-9fd6-6f534f8fede2.png)

**Comment by 4g3v** [comment]
@reiart Unfortunately Fortnite seems to use a completely different format now. Even if it would work, it would only be an old copy of the file and none of the changes will be reflected. This method seems to work fine instead https://www.youtube.com/watch?v=GbIn7FKfphQ

**Comment by AltimorTASDK** [comment]
Updated https://github.com/AltimorTASDK/ClientSettingsEditor/releases/tag/1.6
