### ISSUE TITLE
Targeting Slow Missing?

### ISSUE THREAD

**Issue by TigerEyes16** [AltimorTASDK/ClientSettingsEditor#7]
I can't find the old targeting slow option, in which appeared in the previous versions of the clientsettings, but how in the old version I can't open my settings because this error appears: "unable to read beyond point" I downloaded this new version, but as I said the targeting slow is missing, what should I do to "find it"?

**Comment by AltimorTASDK** [comment]
You have to change the setting in-game so it gets written to the file. You can also duplicate another float property and change the name to TargetingSlow.

**Comment by TigerEyes16** [comment]
I changed the name to Targeting slow, was it supposed to give a value to the Targeting slow? Because, it just kept the same value as the float that I copied

**Comment by AltimorTASDK** [comment]
You have to change the value yourself.
