### ISSUE TITLE
failed to deserialize file issue

### ISSUE THREAD

**Issue by RarriFn** [AltimorTASDK/ClientSettingsEditor#70]
Are they ever gonna fix this ?

**Comment by Decervel** [comment]
Hello developers program Client Settings Editor how to fix a bug  deserialize file?

**Comment by 4g3v** [comment]
I might have fixed this issue. Use this version and tell me if there are still any problems.
https://github.com/4g3v/ClientSettingsEditor/releases/tag/1.6

**Comment by RarriFn** [comment]
@4g3v i tried it and it still didn’t work

**Comment by 4g3v** [comment]
@RarriFn Can you provide me your ClientSettings.Sav file?

**Comment by RarriFn** [comment]
@4g3v 

file:///C:/Users/ramir/AppData/Local/FortniteGame/Saved/SaveGames/ClientSettings.Sav

**Comment by vanillo1337** [comment]
скачал исправленную версию, но к сожалению она не работает тоже, исправьте пожалуйста, ну или на крайний случай скажите как узнать полную сенсу в игре fortnite, в каком файле находится эта строка

**Comment by 4g3v** [comment]
@vanillo1337 я использую гугл переводчик. К сожалению, сейчас Fortnite использует совершенно другой формат. Даже если это сработает, это будет только старая копия файла, и ни одно из изменений не будет отражено. Этот метод, кажется, работает нормально вместо https://www.youtube.com/watch?v=GbIn7FKfphQ

**Comment by TobyGottschalk** [comment]
Same problem

**Comment by AltimorTASDK** [comment]
Updated https://github.com/AltimorTASDK/ClientSettingsEditor/releases/tag/1.6
