### ISSUE TITLE
Failed to deserialize file.

### ISSUE THREAD

**Issue by volkolol** [AltimorTASDK/ClientSettingsEditor#72]
when i try to open sav it is saying : Failed to deserialize file. Exception : Unable to read beyond the end of the stream.
Pls help me :(
(i tried everything, latest version and stuff, didn't work :(]

**Comment by filip-muller** [comment]
Same here, did you happen to find any way to fix it?

**Comment by AltimorTASDK** [comment]
This is out of date

**Comment by filip-muller** [comment]
And is there any chance you'll update it in the future? I would be very glad as I haven't found anything else of this kind and found it extremely useful<3.

**Comment by AltimorTASDK** [comment]
Updated https://github.com/AltimorTASDK/ClientSettingsEditor/releases/tag/1.6
