### ISSUE TITLE
Won't load

### ISSUE THREAD

**Issue by Riddik1E90FF** [AltimorTASDK/ClientSettingsEditor#74]
I download it and open it. extract files. import from cloud. and epic games login doesn't load. just sits there.

**Comment by AltimorTASDK** [comment]
This is way out of date.

**Comment by Riddik1E90FF** [comment]
Dang you right bro lol

**Comment by AltimorTASDK** [comment]
Updated https://github.com/AltimorTASDK/ClientSettingsEditor/releases/tag/1.6
