### ISSUE TITLE
The page wont open.

### ISSUE THREAD

**Issue by Nischal-10** [AltimorTASDK/ClientSettingsEditor#75]
I cant cloud import my fortnite sens nor can I open the client setting. DO something

**Comment by AltimorTASDK** [comment]
This is out of date

**Comment by Nischal-10** [comment]
So how can I get one to get my sens?

**Comment by clearbucketLabs** [comment]
> So how can I get one to get my sens?

you dont.

**Comment by AltimorTASDK** [comment]
Updated https://github.com/AltimorTASDK/ClientSettingsEditor/releases/tag/1.6
