### ISSUE TITLE
1.6 beta

### ISSUE THREAD

**Issue by necroahmed** [AltimorTASDK/ClientSettingsEditor#76]
hi Mr altimortasdk

thx for the amazing tools 

i have  idea

can u make beta version of Clint setting editor plz "1.6 beta " 

allow the user to just change the sensitivity  

plz update the tool to allow us to just change the  sensitivity sitting , dont update the key map or any thing just let us access to the x y & ads scope sensitivity 

the beta version 1.6  no need to be perfect for all sitting , we just want the  sensitivity sitting  

i hope you understand me , and sorry if my English lang not very clear cause im Arabian 

thx mr 
beast regard

**Comment by AltimorTASDK** [comment]
Updated https://github.com/AltimorTASDK/ClientSettingsEditor/releases/tag/1.6
