### ISSUE TITLE
Failed to deserialize file error since patch 10.30

### ISSUE THREAD

**Issue by b0hnz** [AltimorTASDK/ClientSettingsEditor#8]
Hello guys, everything is in the title, can't open the Clientsettings.sav. The error is "Failed to deserialize" or "failed to open".

What should I do?

**Comment by madethisfortheissue** [comment]
same here, i can get into my xbox sav for some reason but not into my pc sav.

**Comment by AltimorTASDK** [comment]
Could someone upload a copy of their ClientSettings.sav after the patch?

**Comment by r3ggie95** [comment]
Do you still need someone to upload a save?

**Comment by kukulkn27** [comment]
I'm having the same issue. 

I can import the console's sav but not my (pc) clientsettings.sav. When i try to import the file it just doesn't display anything. Also what i noticed is the date shown on the last modified is wrong, is a full day ahead. For example I last modified the file yesterday(9/10/19) before 10.30 update and today (9/11/10) it says the last modified files was saved on 9/12/19 !?!?

 Luckily i had a backup clientsettings.sav file from one of my previous changes, i opened it changed some things  and successfully exported the file. The changes did take in effect in the game but when i open ClientSettings Editor again and tried to import the sav file it still doesn't work and the sav file that i modified/exported today still has the wrong date showing 9/12/19.

Btw i'm using the latest v1.4 build of ClientSettings Editor.

plz help =)

**Comment by b0hnz** [comment]
Here is a copy of ma sav.
[ClientSettings.zip](https://github.com/AltimorTASDK/ClientSettingsEditor/files/3605749/ClientSettings.zip)

**Comment by Coolie718** [comment]
hey, here is a link of my save made after the update cannot access.

https://gofile.io/?c=qEAmUA

**Comment by bostinha222** [comment]
> I'm having the same issue.
> 
> I can import the console's sav but not my (pc) clientsettings.sav. When i try to import the file it just doesn't display anything. Also what i noticed is the date shown on the last modified is wrong, is a full day ahead. For example I last modified the file yesterday(9/10/19) before 10.30 update and today (9/11/10) it says the last modified files was saved on 9/12/19 !?!?
> 
> Luckily i had a backup clientsettings.sav file from one of my previous changes, i opened it changed some things and successfully exported the file. The changes did take in effect in the game but when i open ClientSettings Editor again and tried to import the sav file it still doesn't work and the sav file that i modified/exported today still has the wrong date showing 9/12/19.
> 
> Btw i'm using the latest v1.4 build of ClientSettings Editor.
> 
> plz help =)

Having The same issue..

**Comment by 00AhmedAshraf** [comment]
I think this problem needs a new version of application because this version support only Fortnite 9.1

**Comment by AltimorTASDK** [comment]
ClientSettings.sav is now encrypted, so this isn't as simple of a fix as before.

**Comment by Coolie718** [comment]
> ClientSettings.sav is now encrypted, so this isn't as simple of a fix as before.

Hey man, 

Please take as much time as you need. We all appreciate the program u created to help everyone. If you need any other saves please let me know.

**Comment by nobodygivesadamn** [comment]
Try using the following AES key to decrypt: 0xccbbaddb24a0d16c14088ab762ca93dadfd3cb773619cbf49a05a3bcc5ad920d

They could be using the same one for it as they use for pak files, worth a shot I suppose. However, if they do, app will have to be updated every time fortnite does.

**Comment by AltimorTASDK** [comment]
Fixed
