### ISSUE TITLE
Could you update this?

### ISSUE THREAD

**Issue by Not-a-Tyler** [AltimorTASDK/ClientSettingsEditor#84]
I'm getting error Failed to deserialize file. Exception: Unable to read beyond the end of the stream.

**Comment by AltimorTASDK** [comment]
Nah sorry, I haven't touched Fortnite in many years.

**Comment by AltimorTASDK** [comment]
Updated https://github.com/AltimorTASDK/ClientSettingsEditor/releases/tag/1.6
