### ISSUE TITLE
Failed To Open File

### ISSUE THREAD

**Issue by DarkViper417** [AltimorTASDK/ClientSettingsEditor#9]
Hi,I get this issue every time I try to open my saved file ,it says "Failed To Open File" Help appreciated thanks

**Comment by diogovk** [comment]
I'm having the same problem 
[ClientSettings.zip](https://github.com/AltimorTASDK/ClientSettingsEditor/files/3608093/ClientSettings.zip)

**Comment by bostinha222** [comment]
me too, please help

**Comment by bostinha222** [comment]
I Hope he helps us..

**Comment by yugosmurff** [comment]
same here, it's not working anymore

**Comment by NNoah18** [comment]
it is also not working for me

**Comment by xondtz** [comment]
já se passo 6 dias é nada de correção

**Comment by diogovk** [comment]
Guys... On reddit they mentioned that Epic encrypted the file, so this is not an easy fix.
The developer is aware of the problem. 
The recommendation is to use Fortnite Slider for now to configure Kovaak's.
See this post:
https://www.reddit.com/r/FPSAimTrainer/comments/d47g8u/i_cant_use_kovaaks_because_i_cant_get_my_fortnite/
and this post:
https://www.reddit.com/r/FPSAimTrainer/comments/d5amsk/stop_spamming_ualtimor/

**Comment by AltimorTASDK** [comment]
Fixed
